name: cartoonize
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # image_editor_pro: ^1.1.8
  custom_image_crop: ^0.0.4
  dio: ^4.0.6
  rxdart: ^0.27.5
  image_picker: ^0.8.5+3
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  image_gallery_saver: ^1.7.1
  photo_view: ^0.14.0
  octo_image: ^1.0.2
  image_cropper: ^3.0.0
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.1
  permission_handler: ^10.0.0
  flutter_hooks: ^0.18.5+1
  intro_slider: ^3.0.10
  carousel_slider: ^4.1.1
  share_plus: ^4.0.10+1
  flutter_staggered_grid_view: ^0.6.2
  sqflite: ^2.0.3+1
  google_fonts: ^3.0.1
  connectivity_plus: ^2.3.6+1
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  package_info_plus: ^1.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
         - asset: fonts/OpenSans.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
